name: Cache

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: resolveCache
        with:
          path: ./package-lock.json
          key: packlock
      - run: echo "Cache resolved ${{ steps.resolveCache.outputs.cache-hit }}"