name: Deploy by assigning labels

on:
  pull_request:
    types:
      - labeled

    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Show label
        run: echo "Label ${{ github.event.label.name }} was assigned to PR"

  deploy_staging:
    needs: [report]
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'deploy_staging' }}
    steps:
      - name: Deploy to staging
        run: echo "Deploy to staging..."