name: Print secrets

on: [workflow_dispatch]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Print secrets:"
      - name: Hello world action step
        uses: ./.github/actions/do-action # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'