name: Test reusable workflow

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      name: ${{ inputs.name }}

  report:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.test.outputs.result}}"