name: Test reusable workflow

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    uses: bohdanzhylavskyi/.github/.github/workflows/reusable-workflow.yml@main
    with:
      name: ${{ inputs.name }}

  report:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.test.outputs.result}}"