name: Variables & Secrets

on: [workflow_dispatch]

env:
  workflowEnv: 'workflow-env-value'

jobs:
  inline_variables:
    name: Inline Variables
    runs-on: ubuntu-latest
    steps:
      - name: Show inline variables
        run: |
          echo $workflowEnv
          echo ${{ env.jobEnv }}
    env:
      jobEnv: 'job-env-value'

  variables:
    name: Variables
    runs-on: ubuntu-latest
    steps:
      - name: Show variable
        run: echo ${{ vars.myVariable }}

  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    env:
      wrappedSecret: ${{ secrets.mySecret }}
    steps:
      - name: Show secret
        run: echo ${{ secrets.mySecret }}
      - name: Show secret as variable
        run: |
          echo ${{ env.wrappedSecret }}
          echo $wrappedSecret
      - name: Show string
        run: echo "secretyker"